### ISSUE TITLE
值不正确

### ISSUE THREAD

**Issue by csshuai** [ChristianFF/NotchCompat#1]
https://github.com/ChristianFF/NotchCompat/blob/4708dd4ff9c6a09a4f50ce2caf51e195ed86fa61/library/src/main/kotlin/ff/driven/self/notch/HwNotchScreenSupport.kt#L38

第一个值应该是宽度, 第二个值应该是高度

**Comment by ChristianFF** [comment]
Thanks, fixed in commit [c3d0ad57d9cf44a85131afc35dcc9d007328841b](https://github.com/ChristianFF/NotchCompat/commit/c3d0ad57d9cf44a85131afc35dcc9d007328841b)
